config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'blogs#index'
  resources :blogs, only: [:new, :create, :edit, :destroy]
  
  resources :sessions,only:[:new,:create,:destroy]

  resources :users,only:[:new,:create,:show]
  
  resources :blogs do
    collection do
      post :confirm
    end
   end
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  
  belongs_to :user           
   mount_uploader :image, ImageUploader
  validates :content, length: { in: 1..140 }
  validates :title, presence: true
  validates :image, presence: true

  
  
  
end

app/models/user.rb
class User < ApplicationRecord
  
  
  has_many :blogs
  validates :name, presence: true, length: { maximum: 20 }
  validates :email,presence: true, length: { maximum: 30 },
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: true
 
            
  before_validation { email.downcase! }
  
  has_secure_password
  validates :password_digest, presence:true, length: {minimum: 4}
  
  
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
before_action :set_blog, only: [:show, :edit, :update, :destroy]
 
  def index
    @blogs = Blog.all
  end

  def show
      @blogs = Blog.find(params[:id])
  end

  def new
    @blog = Blog.new
  end

  def edit
    @blogs = Blog.find(params[:id])
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.image.retrieve_from_cache! params[:cache][:image] 
    # @blog.user_id = current_user.id
    
    if @blog.save
      # Switch to the list screen and display a message saying "You have created new blog!"
#       RobMailer.blog_mail(@blog).deliver
      redirect_to blogs_path, Notice: "You have created new blog!"
    else
      # Redraw the input form.
      render 'new'
    end
  end
  
  def confirm
    @blog = current_user.blogs.build(blog_params)
     render :new if @blog.invalid?
  end
  
  
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    
  def set_blog
      @blog = Blog.find(params[:id])
  end

    
  def blog_params
      
      params.require(:blog).permit(:title, :content, :image).merge(user: current_user)
  end
  
end

app/controllers/graphql_controller.rb
class GraphqlController < ApplicationController
  # If accessing from outside this domain, nullify the session
  # This allows for outside API access while preventing CSRF attacks,
  # but you'll have to authenticate your user separately
  # protect_from_forgery with: :null_session

  def execute
    variables = ensure_hash(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      # Query context goes here, for example:
      # current_user: current_user,
      blog: Blog.last
    }
    result = FacebookSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  rescue => e
    raise e unless Rails.env.development?
    handle_error_in_development e
  end

  private

  # Handle form data, JSON body, or a blank value
  def ensure_hash(ambiguous_param)
    case ambiguous_param
    when String
      if ambiguous_param.present?
        ensure_hash(JSON.parse(ambiguous_param))
      else
        {}
      end
    when Hash, ActionController::Parameters
      ambiguous_param
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{ambiguous_param}"
    end
  end

  def handle_error_in_development(e)
    logger.error e.message
    logger.error e.backtrace.join("\n")

    render json: { error: { message: e.message, backtrace: e.backtrace }, data: {} }, status: 500
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end
  
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user=User.new
  end
  
  def create
    @user=User.new(user_params)
    
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end
  
  def show
    @user=User.find(params[:id])
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)      
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
          <% end %>
      </ul>
    </div>
    <% end %>

      <div class="field">
        <%= form.label :title %>
          <%= form.text_field :title, id: :blog_title %>
      </div>

      <div class="field">
        <%= form.label :image %>
          <%= form.file_field :image, id: :blog_image %>
      </div>

      <div class="field">
        <%= form.label :content %>
          <%= form.text_area :content, id: :blog_content %>
      </div>

      <div class="actions">
        <%= form.submit %>
      </div>
      <% end %>

        <%= link_to "Return to List of blogs screen", blogs_path %>

app/views/blogs/confirm.html.erb
<h3>Comfirm</h3>

<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
    <%= form.hidden_field :content %>

      <p>Title:
        <%= @blog.title %>
      </p>
      <p>Body:
        <%= @blog.content %>
      </p>
      <p>Body:
        <%= image_tag(@blog.image.url(:thumb)) %>
      </p>
      <%= hidden_field_tag :"cache[image]",@blog.image.cache_name%>
        <%= form.submit  "submit" %>
          <% end %>

            <%= form_with(model: @blog, url: new_blog_path, local: true, method: 'get') do |form| %>
              <%= form.hidden_field :title %>
                <%= form.hidden_field :content %>
                  <%= form.hidden_field :image %>

                    <%= form.submit "Back", name: 'back' %>
                      <% end %>

app/views/blogs/edit.html.erb
<div class="container-fluid">
  <% if logged_in? %>
<h1>Editing Picture</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>
 <% end %>
</div>

app/views/blogs/index.html.erb
<div class="container-fluid">
 <div class="row">
<p id="notice"><%= notice %></p>

<h1>Pictures</h1>

<table>
  <thead>
    <tr>
      <th>投稿者</th>
      <th>タイトル</th>
     
      <th>投稿内容</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.user.name %></td>
        <td><%= blog.title %></td>
               <td><%= blog.content %></td>
        <td><%= link_to 'Show', blog %></td>
       
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
   
  </tbody>
</table>
  </div>
   </div>
<br>

 <% end %>
  
</div>

app/views/blogs/new.html.erb
<div class="container-fluid">

<% if logged_in? %>
  <h1>New Picture</h1>
<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>
  <% end %>
</div>

app/views/blogs/show.html.erb
<div class="container-fluid">
  <div class="row">

    <p>
      <strong>Title:</strong>
      <%= @blog.title %>
    </p>

    <p>
      <strong>Image:</strong>
      <%= image_tag @blog.image.url, style:'width:300px;height:300px;' %>
    </p>

    <p>
      <strong>Content:</strong>
      <%= @blog.content %>
    </p>

    <%= link_to 'Edit', edit_blog_path(@blog) %> |
      <%= link_to 'Back', blogs_path %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Facebook</title>
  <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
            <span class="sr-only">Nze Facebook</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        <a class="navbar-brand" href="#">Nze facebook</a>
      </div>

      <div id="gnavi" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><a href="/">HOME</a></li>
          <li><a href="/blogs/new">New Post！！</a></li>
          <li><a href="/blogs">List Of Posts</a></li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="login">
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
        <% end %>

          <% if logged_in? %>
            <%= link_to "Profile", user_path(current_user.id) %>
              <%= link_to "Logout", session_path(current_user.id), method: :delete %>
                <% else %>
                  <%= link_to "Sign up", new_user_path %>
                    <%= link_to "Login", new_session_path %>
                      <% end %>
  </div>
  <div class="container-fluid">
    <div class="row">
    </div>
  </div>

  <%= yield %>


    <div class="footer">
      <p>This is me</p>

      <p>2018</p>

    </div>

</body>

</html>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= @user.errors.count %>errors occurred.</h2>
      <ul>

        <% @user.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
      </ul>
    </div>
    <% end %>
      <%= form_with(model: @user, local: true) do |f| %>
        <%= f.label :name %>
          <%= f.text_field :name %>

            <%= f.label :email %>
              <%= f.email_field :email %>

                <%= f.label :password %>
                  <%= f.password_field :password %>

                    <%= f.label :password_confirmation %>
                      <%= f.password_field :password_confirmation %>

                        <%= f.submit "Create my account" %>
                          <% end %>

app/views/users/new.html.erb
<div class="container-fluid">
  <h1>Sign up</h1>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
          <% end %>
      </ul>
    </div>
    <% end %>

      <%= form_with(model: @user, local: true) do |f| %>
        <%= f.label :name %>
          <%= f.text_field :name %>

            <%= f.label :email %>
              <%= f.email_field :email %>

                <%= f.label :password %>
                  <%= f.password_field :password %>

                    <%= f.label :password_confirmation %>
                      <%= f.password_field :password_confirmation %>

                        <%= f.submit "Create my account" %>
                          <% end %>

</div>

app/views/users/show.html.erb
<div class="container-fluid">
  <h1>
    <%= @user.name %>さんのプロフィール</h1>

  <p>メールアドレス:
    <%= @user.email %>
  </p>

</div>